export const DATA_SOURCE = 'DATA_SOURCE';
export const DEVELOPMENT = 'DEVELOPMENT';
export const TESTING = 'TESTING';
export const PRODUCTION = 'PRODUCTION';

// Repositories
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const PROD_CAT_REPOSITORY = 'PROD_CAT_REPOSITORY';
